bool isBehindDCDC(int LYR, bool BmI, bool BpI, bool BpO, bool BmO, int SEC, int LDR, int MOD, int ROC, int DSK, int BLD, int PNL, int RNG){
return (LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==0) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==1) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==12) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==13) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==14) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==15) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==2) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==3) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==10) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==11) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==4) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==5) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==6) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==7) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==8) ||
(LYR==1 && BmI && SEC==1 && LDR==1 && MOD==4 && ROC==9) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==0) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==1) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==10) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==11) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==12) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==13) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==14) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==15) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==2) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==3) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==4) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==5) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==6) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==7) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==8) ||
(LYR==3 && BmI && SEC==2 && LDR==3 && MOD==4 && ROC==9) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==0) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==1) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==10) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==11) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==12) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==13) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==14) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==15) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==2) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==3) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==4) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==5) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==6) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==7) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==8) ||
(LYR==2 && BmI && SEC==7 && LDR==11 && MOD==4 && ROC==9) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==0) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==1) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==10) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==11) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==12) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==13) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==14) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==15) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==2) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==3) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==4) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==5) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==6) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==7) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==8) ||
(LYR==2 && BmI && SEC==7 && LDR==12 && MOD==1 && ROC==9) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==0) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==1) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==10) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==11) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==12) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==13) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==14) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==15) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==2) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==3) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==4) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==5) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==6) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==7) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==8) ||
(LYR==2 && BmI && SEC==8 && LDR==13 && MOD==4 && ROC==9) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==0) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==1) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==10) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==11) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==12) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==13) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==14) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==15) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==2) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==3) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==4) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==5) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==6) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==7) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==8) ||
(LYR==2 && BmI && SEC==8 && LDR==14 && MOD==1 && ROC==9) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==0) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==1) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==10) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==11) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==12) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==13) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==14) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==15) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==2) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==3) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==4) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==5) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==6) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==7) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==8) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==2 && ROC==9) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==0) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==1) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==10) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==11) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==12) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==13) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==14) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==15) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==2) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==3) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==4) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==5) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==6) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==7) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==8) ||
(LYR==2 && BmO && SEC==3 && LDR==5 && MOD==3 && ROC==9) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==0) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==1) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==10) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==11) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==12) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==13) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==14) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==15) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==2) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==3) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==4) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==5) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==7) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==8) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==1 && ROC==9) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==1) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==10) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==11) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==12) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==13) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==14) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==2) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==3) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==4) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==8) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==2 && ROC==9) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==1) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==10) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==11) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==12) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==13) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==14) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==2) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==3) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==4) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==5) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==6) ||
(LYR==2 && BpI && SEC==1 && LDR==1 && MOD==3 && ROC==9) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==0) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==1) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==12) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==13) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==14) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==15) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==2) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==3) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==10) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==11) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==4) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==5) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==6) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==7) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==8) ||
(LYR==1 && BpI && SEC==4 && LDR==3 && MOD==2 && ROC==9) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==0) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==1) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==10) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==11) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==12) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==13) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==14) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==15) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==2) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==3) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==4) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==5) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==6) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==7) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==8) ||
(LYR==2 && BpI && SEC==4 && LDR==7 && MOD==1 && ROC==9) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==0) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==1) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==10) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==11) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==12) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==13) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==14) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==15) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==2) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==3) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==4) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==5) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==6) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==7) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==8) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==1 && ROC==9) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==0) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==1) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==10) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==11) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==12) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==13) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==14) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==15) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==2) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==3) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==4) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==5) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==6) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==7) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==8) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==2 && ROC==9) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==0) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==1) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==10) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==11) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==12) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==13) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==14) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==15) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==2) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==3) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==4) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==5) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==6) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==7) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==8) ||
(LYR==2 && BpO && SEC==1 && LDR==1 && MOD==3 && ROC==9) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==12) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==13) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==14) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==15) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==4) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==5) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==6) ||
(LYR==4 && BpO && SEC==8 && LDR==32 && MOD==1 && ROC==7) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==3) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==1 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==12) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==1 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==12) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==3) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==1 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BmI && BLD==10 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BmI && BLD==11 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BmI && BLD==14 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BmI && BLD==9 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BmI && BLD==10 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BmI && BLD==11 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BmI && BLD==11 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BmI && BLD==9 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==1 && BmO && BLD==12 && PNL==1 && RNG==2 && ROC==11) ||
(DSK==1 && BmO && BLD==1 && PNL==2 && RNG==2 && ROC==10) ||
(DSK==1 && BmO && BLD==1 && PNL==2 && RNG==2 && ROC==6) ||
(DSK==1 && BmO && BLD==1 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==1 && BmO && BLD==1 && PNL==2 && RNG==2 && ROC==8) ||
(DSK==1 && BmO && BLD==1 && PNL==2 && RNG==2 && ROC==9) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==10) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==5) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==6) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==8) ||
(DSK==1 && BmO && BLD==2 && PNL==2 && RNG==2 && ROC==9) ||
(DSK==1 && BmO && BLD==3 && PNL==2 && RNG==2 && ROC==6) ||
(DSK==1 && BmO && BLD==3 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==1 && BmO && BLD==3 && PNL==2 && RNG==2 && ROC==8) ||
(DSK==1 && BmO && BLD==3 && PNL==2 && RNG==2 && ROC==9) ||
(DSK==1 && BmO && BLD==4 && PNL==2 && RNG==2 && ROC==7) ||
(DSK==1 && BmO && BLD==4 && PNL==2 && RNG==2 && ROC==8) ||
(DSK==3 && BmO && BLD==12 && PNL==1 && RNG==2 && ROC==9) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==13) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==2) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==1 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==13) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==2 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==2) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==3 && PNL==2 && RNG==1 && ROC==9) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==4 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==5 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==2 && BpI && BLD==6 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpI && BLD==12 && PNL==1 && RNG==2 && ROC==7) ||
(DSK==3 && BpI && BLD==12 && PNL==1 && RNG==2 && ROC==8) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BpI && BLD==7 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==0) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BpI && BLD==8 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpI && BLD==9 && PNL==1 && RNG==2 && ROC==8) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==1 && BpO && BLD==6 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==1 && BpO && BLD==7 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==1 && BpO && BLD==8 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==0) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==15) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BpO && BLD==10 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BpO && BLD==11 && PNL==1 && RNG==1 && ROC==9) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==1) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==10) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==11) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==12) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==13) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==14) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==2) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==3) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==4) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==5) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==6) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==7) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==8) ||
(DSK==3 && BpO && BLD==9 && PNL==1 && RNG==1 && ROC==9);
}
